/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithingsCallbackRouteImport } from './routes/withings/callback'
import { Route as DashProfileRouteImport } from './routes/_dash/profile'
import { Route as DashIntegrationsRouteImport } from './routes/_dash/integrations'
import { Route as DashHomeRouteImport } from './routes/_dash/home'
import { Route as DashExerciseRouteImport } from './routes/_dash/exercise'
import { Route as DashAnalyticsRouteImport } from './routes/_dash/analytics'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashExerciseActivityIdRouteImport } from './routes/_dash/exercise_.$activityId'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithingsCallbackRoute = WithingsCallbackRouteImport.update({
  id: '/withings/callback',
  path: '/withings/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashIntegrationsRoute = DashIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashRoute,
} as any)
const DashHomeRoute = DashHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashRoute,
} as any)
const DashExerciseRoute = DashExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => DashRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashExerciseActivityIdRoute = DashExerciseActivityIdRouteImport.update({
  id: '/exercise_/$activityId',
  path: '/exercise/$activityId',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof DashAnalyticsRoute
  '/exercise': typeof DashExerciseRoute
  '/home': typeof DashHomeRoute
  '/integrations': typeof DashIntegrationsRoute
  '/profile': typeof DashProfileRoute
  '/withings/callback': typeof WithingsCallbackRoute
  '/exercise/$activityId': typeof DashExerciseActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof DashAnalyticsRoute
  '/exercise': typeof DashExerciseRoute
  '/home': typeof DashHomeRoute
  '/integrations': typeof DashIntegrationsRoute
  '/profile': typeof DashProfileRoute
  '/withings/callback': typeof WithingsCallbackRoute
  '/exercise/$activityId': typeof DashExerciseActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dash': typeof DashRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/exercise': typeof DashExerciseRoute
  '/_dash/home': typeof DashHomeRoute
  '/_dash/integrations': typeof DashIntegrationsRoute
  '/_dash/profile': typeof DashProfileRoute
  '/withings/callback': typeof WithingsCallbackRoute
  '/_dash/exercise_/$activityId': typeof DashExerciseActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/exercise'
    | '/home'
    | '/integrations'
    | '/profile'
    | '/withings/callback'
    | '/exercise/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/exercise'
    | '/home'
    | '/integrations'
    | '/profile'
    | '/withings/callback'
    | '/exercise/$activityId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dash'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dash/analytics'
    | '/_dash/exercise'
    | '/_dash/home'
    | '/_dash/integrations'
    | '/_dash/profile'
    | '/withings/callback'
    | '/_dash/exercise_/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashRoute: typeof DashRouteWithChildren
  WithingsCallbackRoute: typeof WithingsCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withings/callback': {
      id: '/withings/callback'
      path: '/withings/callback'
      fullPath: '/withings/callback'
      preLoaderRoute: typeof WithingsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/integrations': {
      id: '/_dash/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashIntegrationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/home': {
      id: '/_dash/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashHomeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/exercise': {
      id: '/_dash/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof DashExerciseRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dash/exercise_/$activityId': {
      id: '/_dash/exercise_/$activityId'
      path: '/exercise/$activityId'
      fullPath: '/exercise/$activityId'
      preLoaderRoute: typeof DashExerciseActivityIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashExerciseRoute: typeof DashExerciseRoute
  DashHomeRoute: typeof DashHomeRoute
  DashIntegrationsRoute: typeof DashIntegrationsRoute
  DashProfileRoute: typeof DashProfileRoute
  DashExerciseActivityIdRoute: typeof DashExerciseActivityIdRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashExerciseRoute: DashExerciseRoute,
  DashHomeRoute: DashHomeRoute,
  DashIntegrationsRoute: DashIntegrationsRoute,
  DashProfileRoute: DashProfileRoute,
  DashExerciseActivityIdRoute: DashExerciseActivityIdRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashRoute: DashRouteWithChildren,
  WithingsCallbackRoute: WithingsCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
