/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashProfileRouteImport } from './routes/_dash/profile'
import { Route as DashIntegrationsRouteImport } from './routes/_dash/integrations'
import { Route as DashHomeRouteImport } from './routes/_dash/home'
import { Route as DashAnalyticsRouteImport } from './routes/_dash/analytics'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashIntegrationsRoute = DashIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashRoute,
} as any)
const DashHomeRoute = DashHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/analytics': typeof DashAnalyticsRoute
  '/home': typeof DashHomeRoute
  '/integrations': typeof DashIntegrationsRoute
  '/profile': typeof DashProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/analytics': typeof DashAnalyticsRoute
  '/home': typeof DashHomeRoute
  '/integrations': typeof DashIntegrationsRoute
  '/profile': typeof DashProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dash': typeof DashRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/home': typeof DashHomeRoute
  '/_dash/integrations': typeof DashIntegrationsRoute
  '/_dash/profile': typeof DashProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/home'
    | '/integrations'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/analytics' | '/home' | '/integrations' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dash'
    | '/_auth/login'
    | '/_dash/analytics'
    | '/_dash/home'
    | '/_dash/integrations'
    | '/_dash/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/integrations': {
      id: '/_dash/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashIntegrationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/home': {
      id: '/_dash/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashHomeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashHomeRoute: typeof DashHomeRoute
  DashIntegrationsRoute: typeof DashIntegrationsRoute
  DashProfileRoute: typeof DashProfileRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashHomeRoute: DashHomeRoute,
  DashIntegrationsRoute: DashIntegrationsRoute,
  DashProfileRoute: DashProfileRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
